#!/usr/bin/env python3
"""
Full deployment script for the jay-chat CloudFormation stack.

Steps:
  1. ACM certificates (us-east-1) with Route53 DNS validation
  2. WAF Web ACLs (us-east-1, CLOUDFRONT scope)
  3. Build Lambda zips from source and upload to S3
  4. Pre-flight check for orphaned retained resources
  5. Deploy CloudFormation stack
  6. Post-deploy Route53 CNAMEs pointing aliases to CloudFront domains
"""

import argparse
import base64
import getpass
import json
import re
import subprocess
import sys
import time
import zipfile
from pathlib import Path

import boto3
from botocore.exceptions import ClientError

TEMPLATE_FILE = "rag_template.yaml"
PARAMETERS_FILE = "parameters.json"
SENTINEL = "{GENERATED BY deploy.py AT RUNTIME}"

BASE_DIR = Path(__file__).parent


# ---------------------------------------------------------------------------
# parameters.json helpers
# ---------------------------------------------------------------------------

def load_params():
    with open(BASE_DIR / PARAMETERS_FILE) as f:
        return json.load(f)  # list of {"ParameterKey": ..., "ParameterValue": ...}


def save_params(params):
    with open(BASE_DIR / PARAMETERS_FILE, "w") as f:
        json.dump(params, f, indent=2)
        f.write("\n")


def get_param(params, key):
    return next((p["ParameterValue"] for p in params if p["ParameterKey"] == key), None)


def set_param(params, key, value):
    for p in params:
        if p["ParameterKey"] == key:
            p["ParameterValue"] = value
            return
    raise KeyError(f"Parameter {key} not found in {PARAMETERS_FILE}")


# ---------------------------------------------------------------------------
# Step 1: ACM certificates
# ---------------------------------------------------------------------------

def ensure_certificate(acm, route53, params, alias_key, arn_key):
    domain = get_param(params, alias_key)
    existing_arn = get_param(params, arn_key)
    if existing_arn == SENTINEL:
        existing_arn = None

    if existing_arn:
        try:
            resp = acm.describe_certificate(CertificateArn=existing_arn)
            status = resp["Certificate"]["Status"]
            if status == "ISSUED":
                print(f"  [{domain}] certificate already ISSUED")
                return
            print(f"  [{domain}] certificate status: {status}")
        except ClientError:
            print(f"  [{domain}] stored ARN not found, requesting new certificate")
            existing_arn = None

    if not existing_arn:
        # Check if a cert already exists for this domain
        paginator = acm.get_paginator("list_certificates")
        found_arn = None
        for page in paginator.paginate(CertificateStatuses=["ISSUED", "PENDING_VALIDATION"]):
            for cert in page["CertificateSummaryList"]:
                if cert["DomainName"] == domain:
                    found_arn = cert["CertificateArn"]
                    break
            if found_arn:
                break

        if found_arn:
            print(f"  [{domain}] found existing certificate {found_arn}")
            existing_arn = found_arn
        else:
            print(f"  [{domain}] requesting new ACM certificate")
            resp = acm.request_certificate(DomainName=domain, ValidationMethod="DNS")
            existing_arn = resp["CertificateArn"]
            print(f"  [{domain}] certificate ARN: {existing_arn}")
            time.sleep(5)  # let AWS populate validation options

        set_param(params, arn_key, existing_arn)
        save_params(params)

    # Create Route53 DNS validation record if not yet validated
    for _ in range(12):
        resp = acm.describe_certificate(CertificateArn=existing_arn)
        cert = resp["Certificate"]
        if cert["Status"] == "ISSUED":
            print(f"  [{domain}] certificate is ISSUED")
            return
        options = cert.get("DomainValidationOptions", [])
        if options and options[0].get("ResourceRecord"):
            record = options[0]["ResourceRecord"]
            break
        print(f"  [{domain}] waiting for validation options...")
        time.sleep(10)
    else:
        raise RuntimeError(f"Timed out waiting for validation options for {domain}")

    zone_id = _find_hosted_zone(route53, domain)
    print(f"  [{domain}] upserting DNS validation record")
    route53.change_resource_record_sets(
        HostedZoneId=zone_id,
        ChangeBatch={"Changes": [{
            "Action": "UPSERT",
            "ResourceRecordSet": {
                "Name": record["Name"],
                "Type": record["Type"],
                "TTL": 300,
                "ResourceRecords": [{"Value": record["Value"]}],
            },
        }]},
    )

    print(f"  [{domain}] waiting for certificate to be issued (may take a few minutes)...")
    waiter = acm.get_waiter("certificate_validated")
    waiter.wait(CertificateArn=existing_arn, WaiterConfig={"Delay": 30, "MaxAttempts": 40})
    print(f"  [{domain}] certificate is now ISSUED")


def _find_hosted_zone(route53, domain):
    parts = domain.split(".")
    for i in range(len(parts) - 1):
        candidate = ".".join(parts[i:]) + "."
        resp = route53.list_hosted_zones_by_name(DNSName=candidate, MaxItems="1")
        zones = resp["HostedZones"]
        if zones and zones[0]["Name"] == candidate:
            return zones[0]["Id"].split("/")[-1]
    raise ValueError(f"No Route53 hosted zone found for {domain}")


# ---------------------------------------------------------------------------
# Step 2: WAF Web ACLs
# ---------------------------------------------------------------------------

def ensure_waf_acl(wafv2, params, name_suffix, arn_key):
    app_name = get_param(params, "AppName")
    acl_name = f"{app_name}-{name_suffix}"
    existing_arn = get_param(params, arn_key)
    if existing_arn == SENTINEL:
        existing_arn = None

    if existing_arn:
        try:
            parts = existing_arn.split("/")
            wafv2.get_web_acl(Name=parts[-2], Scope="CLOUDFRONT", Id=parts[-1])
            print(f"  [{acl_name}] WAF ACL already exists")
            return
        except ClientError:
            print(f"  [{acl_name}] stored ARN not found, creating new ACL")

    # Check by name
    for acl in wafv2.list_web_acls(Scope="CLOUDFRONT").get("WebACLs", []):
        if acl["Name"] == acl_name:
            print(f"  [{acl_name}] found existing WAF ACL")
            set_param(params, arn_key, acl["ARN"])
            save_params(params)
            return

    print(f"  [{acl_name}] creating WAF ACL")
    resp = wafv2.create_web_acl(
        Name=acl_name,
        Scope="CLOUDFRONT",
        DefaultAction={"Allow": {}},
        VisibilityConfig={
            "SampledRequestsEnabled": True,
            "CloudWatchMetricsEnabled": True,
            "MetricName": acl_name,
        },
        Rules=[],
    )
    arn = resp["Summary"]["ARN"]
    print(f"  [{acl_name}] created: {arn}")
    set_param(params, arn_key, arn)
    save_params(params)


# ---------------------------------------------------------------------------
# Step 3: Build Lambda zips and upload to S3
# ---------------------------------------------------------------------------

def build_and_upload_lambdas(s3, params):
    bucket = get_param(params, "LambdaCodeS3Bucket")

    try:
        s3.head_bucket(Bucket=bucket)
        print(f"  S3 bucket {bucket} exists")
    except ClientError:
        print(f"  Creating S3 bucket {bucket}")
        s3.create_bucket(Bucket=bucket)

    _upload_zip(s3, bucket, "rag-node.zip",        _build_node)
    _upload_zip(s3, bucket, "rag-log-indexer.zip", _build_log_indexer)
    _upload_zip(s3, bucket, "rag-signer.zip",      _build_signer)


def _upload_zip(s3, bucket, key, build_fn):
    zip_path = BASE_DIR / key
    build_fn(zip_path)
    print(f"  Uploading {key}")
    s3.upload_file(str(zip_path), bucket, key)


def _build_node(zip_path):
    src = BASE_DIR / "rag-node"
    print(f"  Building rag-node.zip")
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.write(src / "index.mjs", "index.mjs")
        for f in sorted((src / "node_modules").rglob("*")):
            if f.is_file():
                zf.write(f, f.relative_to(src))


def _build_log_indexer(zip_path):
    src = BASE_DIR / "rag-log-indexer"
    print(f"  Building rag-log-indexer.zip")
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.write(src / "lambda_function.py", "lambda_function.py")


def _build_signer(zip_path):
    src = BASE_DIR / "rag-signer"
    print(f"  Building rag-signer.zip")
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.write(src / "index.mjs", "index.mjs")


# ---------------------------------------------------------------------------
# Step 4: Pre-flight check for orphaned retained resources
# ---------------------------------------------------------------------------

def preflight_check(session, params, profile):
    # Pre-flight only matters for fresh deploys — retained resources from a prior
    # stack would block CloudFormation. If a stack already exists, it owns those
    # resources and we're just doing an update; skip the check entirely.
    stack_name = get_param(params, "AppName")
    cfn = session.client("cloudformation")
    try:
        status = cfn.describe_stacks(StackName=stack_name)["Stacks"][0]["StackStatus"]
        if not status.endswith("_FAILED"):
            print(f"  Stack '{stack_name}' exists ({status}) — skipping orphan check")
            return
    except ClientError:
        pass  # stack doesn't exist → run full pre-flight

    app = get_param(params, "AppName")
    issues = []

    s3        = session.client("s3")
    cf        = session.client("cloudfront")
    lam       = session.client("lambda")
    scheduler = session.client("scheduler")
    bedrock   = session.client("bedrock-agent")

    def warn(resource_type, name, delete_cmd):
        issues.append(f"{resource_type} '{name}' already exists.\n    Delete: {delete_cmd}")

    # S3 data bucket
    bucket = f"{app}-rag-chatbot-data"
    try:
        s3.head_bucket(Bucket=bucket)
        warn("S3 bucket", bucket, f"aws s3 rb --force s3://{bucket} --profile {profile}")
    except ClientError:
        pass

    # CloudFront function
    fn = f"{app}-password-protect-logs"
    try:
        resp = cf.describe_function(Name=fn)
        etag = resp["ETag"]
        warn("CloudFront function", fn,
             f"aws cloudfront delete-function --name {fn} --if-match {etag} --profile {profile}")
    except ClientError:
        pass

    # Lambda functions
    for fn_name in [f"{app}-rag-node", f"{app}-rag-log-indexer", f"{app}-rag-signer"]:
        try:
            lam.get_function(FunctionName=fn_name)
            warn("Lambda function", fn_name,
                 f"aws lambda delete-function --function-name {fn_name} --profile {profile}")
        except ClientError:
            pass

    # EventBridge schedules
    for sched in [f"{app}-nightly"]:
        try:
            scheduler.get_schedule(Name=sched)
            warn("EventBridge schedule", sched,
                 f"aws scheduler delete-schedule --name {sched} --profile {profile}")
        except ClientError:
            pass

    # Bedrock knowledge base (check by name)
    kb_name = f"{app}-products-kb"
    try:
        resp = bedrock.list_knowledge_bases(maxResults=50)
        for kb in resp.get("knowledgeBaseSummaries", []):
            if kb["name"] == kb_name:
                warn("Bedrock knowledge base", kb_name,
                     f"aws bedrock-agent delete-knowledge-base --knowledge-base-id {kb['knowledgeBaseId']} --profile {profile}")
                break
    except ClientError:
        pass

    if issues:
        print("\n  Orphaned resources detected — delete them before deploying:\n")
        for issue in issues:
            print(f"  • {issue}\n")
        sys.exit(1)

    print("  No orphaned resources detected")


# ---------------------------------------------------------------------------
# Step 5: Deploy CloudFormation stack
# ---------------------------------------------------------------------------

def deploy_stack(profile, region, stack_name):
    cmd = [
        "aws", "cloudformation", "deploy",
        "--template-file", str(BASE_DIR / TEMPLATE_FILE),
        "--stack-name", stack_name,
        "--parameter-overrides", f"file://{BASE_DIR / PARAMETERS_FILE}",
        "--capabilities", "CAPABILITY_NAMED_IAM",
        "--region", region,
        "--profile", profile,
    ]
    print(f"  Running: {' '.join(cmd)}")
    subprocess.run(cmd, check=True)


# ---------------------------------------------------------------------------
# Step 6: Upload knowledge base files
# ---------------------------------------------------------------------------

def upload_kb_files(s3, kb_files_path, stack_name, sess):
    path = Path(kb_files_path)
    if not path.is_dir():
        print(f"  {kb_files_path} is not a directory, skipping")
        return

    files = [f for f in sorted(path.rglob("*")) if f.is_file()]
    if not files:
        print(f"  No files found in {kb_files_path}")
        return

    cfn = sess.client("cloudformation")
    resp = cfn.describe_stacks(StackName=stack_name)
    outputs = {o["OutputKey"]: o["OutputValue"] for o in resp["Stacks"][0].get("Outputs", [])}
    bucket = outputs.get("DataBucketName")
    kb_id  = outputs.get("KnowledgeBaseId")
    if not bucket:
        print("  Could not find DataBucketName in stack outputs, skipping upload")
        return

    print(f"  Uploading {len(files)} file(s) to s3://{bucket}/knowledgebase-files/")
    for f in files:
        key = f"knowledgebase-files/{f.relative_to(path)}"
        s3.upload_file(str(f), bucket, key)
        print(f"    {f.name} → {key}")

    if not kb_id:
        print("  KnowledgeBaseId not found in stack outputs, skipping sync")
        return

    bedrock = sess.client("bedrock-agent")
    ds_resp = bedrock.list_data_sources(knowledgeBaseId=kb_id, maxResults=1)
    data_sources = ds_resp.get("dataSourceSummaries", [])
    if not data_sources:
        print("  No data sources found for knowledge base, skipping sync")
        return
    ds_id = data_sources[0]["dataSourceId"]

    print(f"  Starting knowledge base sync (KB: {kb_id}, DS: {ds_id})")
    job_resp = bedrock.start_ingestion_job(knowledgeBaseId=kb_id, dataSourceId=ds_id)
    job_id   = job_resp["ingestionJob"]["ingestionJobId"]

    print(f"  Waiting for sync to complete...")
    while True:
        job = bedrock.get_ingestion_job(
            knowledgeBaseId=kb_id, dataSourceId=ds_id, ingestionJobId=job_id
        )["ingestionJob"]
        status = job["status"]
        if status == "COMPLETE":
            stats = job.get("statistics", {})
            print(f"  Sync complete — "
                  f"scanned: {stats.get('numberOfDocumentsScanned', '?')}, "
                  f"indexed: {stats.get('numberOfNewDocumentsIndexed', '?')}, "
                  f"failed: {stats.get('numberOfDocumentsFailed', '?')}")
            break
        if status == "FAILED":
            print(f"  Sync FAILED: {job.get('failureReasons', [])}")
            break
        time.sleep(10)


# ---------------------------------------------------------------------------
# Step 6: Upload frontend (index.html)
# ---------------------------------------------------------------------------

def upload_frontend(s3, stack_name, params, sess):
    html_path = BASE_DIR / "index.html"
    if not html_path.exists():
        print(f"  index.html not found at {html_path}, skipping")
        return

    cfn = sess.client("cloudformation")
    resp = cfn.describe_stacks(StackName=stack_name)
    outputs = {o["OutputKey"]: o["OutputValue"] for o in resp["Stacks"][0].get("Outputs", [])}

    bucket = outputs.get("DataBucketName")
    if not bucket:
        print("  DataBucketName not in stack outputs, skipping frontend upload")
        return

    chatbot_alias = get_param(params, "ChatbotAlias") or stack_name
    api_url = f"https://{chatbot_alias}/api"

    html = html_path.read_text(encoding="utf-8")
    html = re.sub(r"<title>[^<]*</title>",   f"<title>{stack_name}</title>",  html)
    html = re.sub(r"<h1>[^<]*</h1>",         f"<h1>{stack_name}</h1>",        html)
    html = re.sub(r'const API_URL = "[^"]*";', f'const API_URL = "{api_url}";', html)

    s3.put_object(
        Bucket=bucket,
        Key="front/index.html",
        Body=html.encode("utf-8"),
        ContentType="text/html",
    )
    print(f"  Uploaded index.html → s3://{bucket}/front/index.html")


# ---------------------------------------------------------------------------
# Step 7: Post-deploy Route53 CNAMEs
# ---------------------------------------------------------------------------

def post_deploy_dns(session, route53, params, stack_name):
    cfn = session.client("cloudformation")
    resp = cfn.describe_stacks(StackName=stack_name)
    outputs = {o["OutputKey"]: o["OutputValue"] for o in resp["Stacks"][0].get("Outputs", [])}

    for alias_key, output_key in [
        ("ChatbotAlias", "ChatbotDistributionDomain"),
        ("LogsAlias", "LogsDistributionDomain"),
    ]:
        alias = get_param(params, alias_key)
        cf_domain = outputs.get(output_key)
        if not cf_domain:
            print(f"  No stack output for {output_key}, skipping")
            continue

        zone_id = _find_hosted_zone(route53, alias)
        print(f"  Upserting CNAME {alias} → {cf_domain}")
        route53.change_resource_record_sets(
            HostedZoneId=zone_id,
            ChangeBatch={"Changes": [{
                "Action": "UPSERT",
                "ResourceRecordSet": {
                    "Name": alias + ".",
                    "Type": "CNAME",
                    "TTL": 300,
                    "ResourceRecords": [{"Value": cf_domain}],
                },
            }]},
        )


# ---------------------------------------------------------------------------
# Interactive configuration prompt
# ---------------------------------------------------------------------------

def _current_domain(params):
    app   = get_param(params, "AppName") or ""
    alias = get_param(params, "ChatbotAlias") or ""
    prefix = f"{app}."
    if alias.startswith(prefix):
        return alias[len(prefix):]
    parts = alias.split(".", 1)
    return parts[1] if len(parts) > 1 else ""


def _decode_logs_credentials(params):
    encoded = get_param(params, "LogsBasicAuthBase64") or ""
    try:
        decoded = base64.b64decode(encoded).decode("utf-8")
        if ":" in decoded:
            user, pw = decoded.split(":", 1)
            return user, pw
    except Exception:
        pass
    return "", ""


def prompt_deployment_config(params):
    """Prompt for deployment settings, update params in-place, and return (stack_name, kb_files)."""
    print("\n=== Deployment Configuration ===")

    current_stack = get_param(params, "AppName") or "parts-assistant"
    stack_name = input(f"Stack name [{current_stack}]: ").strip() or current_stack

    current_domain = _current_domain(params)
    domain = input(f"Domain [{current_domain}]: ").strip() or current_domain

    current_user, _ = _decode_logs_credentials(params)
    logs_user = input(f"Logs username [{current_user}]: ").strip() or current_user
    logs_pass = getpass.getpass("Logs password (Enter to keep existing): ")
    if logs_pass:
        logs_b64 = base64.b64encode(f"{logs_user}:{logs_pass}".encode()).decode()
    else:
        logs_b64 = get_param(params, "LogsBasicAuthBase64")

    kb_files = input("Knowledge base files directory (Enter to skip): ").strip() or None

    new_chatbot_alias = f"{stack_name}.{domain}"
    new_logs_alias    = f"{stack_name}-logs.{domain}"

    # Reset cert ARNs if the domain changed so deploy.py requests new ones
    if new_chatbot_alias != get_param(params, "ChatbotAlias"):
        set_param(params, "ChatbotAcmCertificateArn", SENTINEL)
    if new_logs_alias != get_param(params, "LogsAlias"):
        set_param(params, "LogsAcmCertificateArn", SENTINEL)

    set_param(params, "AppName",            stack_name)
    set_param(params, "ChatbotAlias",       new_chatbot_alias)
    set_param(params, "LogsAlias",          new_logs_alias)
    set_param(params, "LogsBasicAuthBase64", logs_b64)
    save_params(params)

    return stack_name, kb_files


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Deploy the CloudFormation stack and prerequisites")
    parser.add_argument("--profile", default="bedrock-course", help="AWS profile (default: bedrock-course)")
    parser.add_argument("--region",  default="us-east-1",      help="AWS region (default: us-east-1)")
    args = parser.parse_args()

    profile = args.profile
    region  = args.region

    params = load_params()
    stack_name, kb_files = prompt_deployment_config(params)

    sess    = boto3.Session(profile_name=profile, region_name=region)

    acm     = sess.client("acm",    region_name="us-east-1")
    wafv2   = sess.client("wafv2",  region_name="us-east-1")
    route53 = sess.client("route53")
    s3      = sess.client("s3",     region_name="us-east-1")

    print("\n=== Step 1: ACM Certificates ===")
    ensure_certificate(acm, route53, params, "ChatbotAlias", "ChatbotAcmCertificateArn")
    ensure_certificate(acm, route53, params, "LogsAlias",    "LogsAcmCertificateArn")

    print("\n=== Step 2: WAF Web ACLs ===")
    ensure_waf_acl(wafv2, params, "chatbot-waf", "ChatbotWafAclArn")
    ensure_waf_acl(wafv2, params, "logs-waf",    "LogsWafAclArn")

    print("\n=== Step 3: Lambda packages ===")
    build_and_upload_lambdas(s3, params)

    print("\n=== Step 4: Pre-flight check ===")
    preflight_check(sess, params, profile)

    print("\n=== Step 5: Deploy CloudFormation stack ===")
    deploy_stack(profile, region, stack_name)

    print("\n=== Step 6: Upload frontend ===")
    upload_frontend(s3, stack_name, params, sess)

    if kb_files:
        print("\n=== Step 7: Upload knowledge base files ===")
        upload_kb_files(s3, kb_files, stack_name, sess)

    print("\n=== Step 8: Post-deploy DNS ===")
    post_deploy_dns(sess, route53, params, stack_name)

    print("\nDone.")


if __name__ == "__main__":
    main()
